# Generated by Django 2.2.4 on 2019-08-30 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costumer',
            options={'ordering': ['first_name', 'last_name', 'amka']},
        ),
    ]
