# Generated by Django 2.2.4 on 2020-01-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0003_auto_20200117_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='eponimia',
            field=models.CharField(max_length=240, null=True, verbose_name='Επωνυμια'),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='amka',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ψευδονυμο'),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ονομα'),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Επιθετο'),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='transport',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Μεταφορικο Μεσο'),
        ),
    ]
