# Generated by Django 2.2.4 on 2020-01-23 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0004_auto_20200117_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costumer',
            options={'ordering': ['eponimia', 'afm']},
        ),
    ]
