# Generated by Django 2.2 on 2020-03-05 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0006_costumerdetails_invoiceitem_paymentinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinvoice',
            name='costumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='costumers.Costumer'),
        ),
    ]
