# Generated by Django 2.2 on 2020-03-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0008_auto_20200305_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
