# Generated by Django 2.2 on 2020-03-05 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0009_auto_20200305_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumerdetails',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='costumers.PaymentInvoice'),
        ),
    ]
