# Generated by Django 3.0.1 on 2020-03-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0011_auto_20200306_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinvoice',
            name='order_type',
            field=models.CharField(choices=[('a', 'Τιμολογιο')], default='a', max_length=1),
        ),
    ]
