# Generated by Django 2.2.6 on 2020-03-06 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0012_paymentinvoice_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('eponimia', models.CharField(max_length=200)),
                ('job', models.TextField()),
                ('afm', models.CharField(max_length=10)),
                ('doy', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('tk', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='card_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costumers.MyCard'),
        ),
    ]
