# Generated by Django 2.2 on 2020-03-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0013_auto_20200306_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycard',
            name='tk',
        ),
        migrations.AddField(
            model_name='mycard',
            name='email',
            field=models.EmailField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mycard',
            name='fax',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mycard',
            name='zipcode',
            field=models.CharField(default='', max_length=10, verbose_name='TK'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mycard',
            name='afm',
            field=models.CharField(max_length=10, verbose_name='ΑΦΜ'),
        ),
        migrations.AlterField(
            model_name='mycard',
            name='city',
            field=models.CharField(max_length=150, verbose_name='ΠΟλη'),
        ),
        migrations.AlterField(
            model_name='mycard',
            name='doy',
            field=models.CharField(max_length=150, verbose_name='ΔΟΥ'),
        ),
        migrations.AlterField(
            model_name='mycard',
            name='eponimia',
            field=models.CharField(max_length=200, verbose_name='Επωνυμια'),
        ),
        migrations.AlterField(
            model_name='mycard',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='Προτεινομενο'),
        ),
        migrations.AlterField(
            model_name='mycard',
            name='job',
            field=models.TextField(verbose_name='Περιγραφη Επαγγελματος'),
        ),
        migrations.AlterField(
            model_name='mycard',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Τηλεφωνα'),
        ),
        migrations.AlterField(
            model_name='mycard',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Τιτλος'),
        ),
    ]
