# Generated by Django 2.2 on 2020-03-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0014_auto_20200307_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='clean_value',
            field=models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Αξια'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=17, verbose_name='Ποσότητα'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='taxes_value',
            field=models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Αξια ΦΠΑ'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_clean_value',
            field=models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Καθαρη Αξια'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_value',
            field=models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Τελικη Αξία'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Τιμή'),
        ),
        migrations.AlterField(
            model_name='mycard',
            name='city',
            field=models.CharField(max_length=150, verbose_name='Εδρα'),
        ),
    ]
