# Generated by Django 2.2 on 2020-03-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0017_auto_20200307_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumerdetails',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Τηλεφωνα'),
        ),
    ]
