# Generated by Django 2.2 on 2020-03-07 13:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0018_costumerdetails_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinvoice',
            name='notes',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
