# Generated by Django 2.2 on 2020-03-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0019_paymentinvoice_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='order_type',
            field=models.CharField(choices=[('a', 'Τιμολογιο'), ('b', 'Δελτιο Παραγγελίας'), ('c', 'Προπαραγγελία')], default='a', max_length=1),
        ),
    ]
