# Generated by Django 3.0.1 on 2020-03-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0021_auto_20200308_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(verbose_name='Ημερομηνία'),
        ),
    ]
