# Generated by Django 3.0.1 on 2020-03-09 04:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0024_auto_20200308_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 9, 4, 24, 51, 790358, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
