# Generated by Django 3.0.1 on 2020-03-09 04:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0025_auto_20200309_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 9, 4, 28, 15, 212142, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
