# Generated by Django 3.0.1 on 2020-05-15 04:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0028_auto_20200405_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinvoice',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Κλειδωμενο'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 4, 50, 32, 457238, tzinfo=utc), verbose_name='Ημερομηνία'),
        ),
    ]
