# Generated by Django 3.0.1 on 2020-05-17 08:06

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_expired', models.DateField(verbose_name='Ημερομηνια')),
                ('sum_z', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Ζ Ημερας')),
                ('pos', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Συνολο POS')),
                ('order_cost', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Συνολο Τιμολογιων')),
                ('extra', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Επιπλεον Εσοδα')),
                ('notes', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Σημειωσεις')),
                ('logistic_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Λογιστικο Συνολο')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Πραγματικο Συνολο')),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Μετρητα')),
            ],
            options={
                'ordering': ['-date_expired'],
            },
        ),
    ]
