# Generated by Django 2.2.4 on 2020-01-07 09:55

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_expired', models.DateField()),
                ('sum_z', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pos', models.DecimalField(decimal_places=2, max_digits=20)),
                ('order_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('extra', models.DecimalField(decimal_places=2, max_digits=20)),
                ('notes', tinymce.models.HTMLField(blank=True, null=True)),
                ('logistic_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
    ]
