# Generated by Django 3.0.1 on 2020-05-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='category',
            field=models.CharField(choices=[('a', 'Αντικαταβολή'), ('b', 'Τραπεζική ΚατάΘεση')], max_length=1, verbose_name='Κατηγορια'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Ονομασια'),
        ),
    ]
