# Generated by Django 2.2.4 on 2020-01-17 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalexpense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general_expenses.GeneralExpenseCategory', verbose_name='Κατηγορια'),
        ),
        migrations.AlterField(
            model_name='generalexpense',
            name='date',
            field=models.DateField(verbose_name='Ημερομηνια'),
        ),
        migrations.AlterField(
            model_name='generalexpense',
            name='is_paid',
            field=models.BooleanField(default=True, verbose_name='Πληρωμενο;'),
        ),
        migrations.AlterField(
            model_name='generalexpense',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Περιγραφη'),
        ),
        migrations.AlterField(
            model_name='generalexpense',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Αξια'),
        ),
        migrations.AlterField(
            model_name='generalexpensecategory',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Ονομασια'),
        ),
    ]
