# Generated by Django 3.0.1 on 2020-02-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_expenses', '0002_auto_20200117_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalexpense',
            name='paid_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Πληρωτεο Ποσο'),
            preserve_default=False,
        ),
    ]
