# Generated by Django 2.2.4 on 2020-01-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billcategory',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Ονομασια'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='category',
            field=models.CharField(choices=[('1', 'Μισθός'), ('2', 'ΙΚΑ'), ('3', 'ΑΣΦΑΛΙΣΤΙΚΕΣ ΕΙΣΦΟΡΕΣ'), ('4', 'ΗΜΕΡΟΜΗΣΘΙΟ'), ('5', 'ΕΡΓΟΣΗΜΟ'), ('6', 'ΔΩΡΟ')], default='1', max_length=1, verbose_name='Κατηγορια'),
        ),
    ]
