# Generated by Django 3.0.1 on 2020-03-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20200107_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Τίτλος'),
        ),
    ]
