# Generated by Django 3.0.1 on 2020-03-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20200309_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Τίτλος'),
        ),
    ]
