# Generated by Django 3.0.1 on 2020-04-05 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20200309_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='payroll.Person')),
            ],
        ),
    ]
