# Generated by Django 3.0.1 on 2020-05-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_personschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personschedule',
            options={'ordering': ['-date_start']},
        ),
        migrations.AlterField(
            model_name='personschedule',
            name='date_end',
            field=models.DateTimeField(verbose_name='Μεχρι'),
        ),
        migrations.AlterField(
            model_name='personschedule',
            name='date_start',
            field=models.DateTimeField(verbose_name='Απο'),
        ),
    ]
