# Generated by Django 2.2.4 on 2019-08-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ενεργό'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='owner',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ιδιοκτήτης'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Εταιρία'),
        ),
    ]
