# Generated by Django 2.2.4 on 2019-09-07 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
        ('vendors', '0003_auto_20190830_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbankingaccount',
            name='code',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vendorbankingaccount',
            name='iban',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='vendorbankingaccount',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='vendorbankingaccount',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banking_accounts', to='frontend.PaymentMethod'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='vendors.Vendor'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(verbose_name='Ημερομηνια'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, verbose_name='Λεπτομεριες'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Ονομασια'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Αξια'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='vendors.Vendor', verbose_name='Προμηθευτης'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, verbose_name='Περιγραφή'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Τίτλος'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Αξία'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='vendors.Vendor', verbose_name='Προμηθευτής'),
        ),
    ]
