# Generated by Django 2.2.4 on 2019-09-10 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
        ('vendors', '0004_auto_20190907_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='frontend.PaymentMethod', verbose_name='Τροπος Πληρωμής'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='frontend.PaymentMethod', verbose_name='Τροπος Πληρωμής'),
        ),
        migrations.AlterField(
            model_name='vendorbankingaccount',
            name='code',
            field=models.CharField(blank=True, max_length=200, verbose_name='Αριθμός Λογαριασμού'),
        ),
        migrations.AlterField(
            model_name='vendorbankingaccount',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ονομα Δικαιούχου'),
        ),
        migrations.AlterField(
            model_name='vendorbankingaccount',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banking_accounts', to='frontend.PaymentMethod', verbose_name='Τροπος Πληρωμής'),
        ),
        migrations.AlterField(
            model_name='vendorbankingaccount',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankings', to='vendors.Vendor', verbose_name='Προμηθευτής'),
        ),
    ]
