# Generated by Django 2.2.4 on 2019-09-17 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_auto_20190913_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='extra_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Επιπλέον Αξία'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='final_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Αξία'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='cellphone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Κινητο'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Τηλεφωνο'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Ονομασια'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='vendors.Vendor', verbose_name='Προμηθευτης'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='frontend.PaymentMethod', verbose_name='Τροπος Πληρωμης'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Καθαρή Αξια'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Διευθυνση'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='afm',
            field=models.CharField(blank=True, max_length=150, verbose_name='ΑΦΜ'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50, verbose_name='Υπόλοιπο'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='cellphone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Κινητό'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='city',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Πολη'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Λεπτομεριες'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='doy',
            field=models.CharField(blank=True, max_length=150, verbose_name='ΔΟΥ'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Σταθερο Τηλεφωνο'),
        ),
    ]
