# Generated by Django 2.2.4 on 2019-09-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_auto_20190917_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='final_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Αξία'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Αριθμος Τιμολογιου'),
        ),
    ]
