# Generated by Django 2.2.4 on 2019-09-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_auto_20190917_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Ονομασια'),
        ),
    ]
