# Generated by Django 2.2.4 on 2019-09-21 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_auto_20190918_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['-title']},
        ),
    ]
