# Generated by Django 2.2.4 on 2019-12-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0014_auto_20191109_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='taxes_modifier',
            field=models.CharField(choices=[('a', 0), ('b', 13), ('c', 24)], default='c', max_length=1),
        ),
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Κατάσταση'),
        ),
    ]
