# Generated by Django 3.0.1 on 2020-05-17 08:06

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costumers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(verbose_name='Ημερομηνία')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Τίτλος')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Ποσό')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='costumers.Costumer', verbose_name='Πελάτης')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(verbose_name='Ημερομηνία')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Τίτλος')),
                ('description', tinymce.models.HTMLField(blank=True, verbose_name='Περιγραφή')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Ποσό')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='costumers.Costumer', verbose_name='Πελάτης')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
