# Generated by Django 3.0.1 on 2020-03-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200308_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
