# Generated by Django 2.2.4 on 2020-02-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='tag',
            field=models.ManyToManyField(blank=True, to='notebook.Tags'),
        ),
    ]
