# Generated by Django 2.2.4 on 2020-02-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_auto_20200204_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
