# Generated by Django 2.2 on 2020-02-15 09:57

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_auto_20200204_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notebook',
            options={'ordering': ['-pinned', '-timestamp']},
        ),
        migrations.AlterField(
            model_name='notebook',
            name='color',
            field=models.CharField(choices=[('a', 'yellow'), ('b', 'white'), ('c', 'green'), ('d', 'red'), ('e', 'blue')], default='a', max_length=1, verbose_name='Χρωμα'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Περιγραφη'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='Καρφιτσωμενο'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='title',
            field=models.CharField(max_length=400, verbose_name='Ονομασια'),
        ),
    ]
