# Generated by Django 2.2.4 on 2019-09-10 16:52

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0006_auto_20190910_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Ονομασια')),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('barcode', models.CharField(blank=True, max_length=20)),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='Ποσότητα')),
                ('price_buy', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Αξία Αγορας')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Αρχική Τιμή Πώλησης')),
                ('value_discount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='')),
                ('final_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('categories', models.ManyToManyField(to='products.Category', verbose_name='Κατηγορίες')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=150)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='vendors',
            field=models.ManyToManyField(through='products.ProductVendor', to='vendors.Vendor', verbose_name='Προμηθευτές'),
        ),
    ]
