# Generated by Django 2.2.4 on 2019-09-13 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvendor',
            name='qty',
        ),
        migrations.AddField(
            model_name='productvendor',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Εκπτωση'),
        ),
        migrations.AlterField(
            model_name='productvendor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Προϊόν'),
        ),
        migrations.AlterField(
            model_name='productvendor',
            name='sku',
            field=models.CharField(max_length=150, verbose_name='Ποσότητα'),
        ),
        migrations.AlterField(
            model_name='productvendor',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Τιμή Μονάδας'),
        ),
        migrations.AlterField(
            model_name='productvendor',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor', verbose_name='Προμηθευτής'),
        ),
    ]
