# Generated by Django 2.2.4 on 2019-09-13 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190913_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvendor',
            name='final_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Καθαρη Αξια'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvendor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Προϊον'),
        ),
        migrations.AlterField(
            model_name='productvendor',
            name='sku',
            field=models.CharField(max_length=150, verbose_name='Ποσοτητα'),
        ),
        migrations.AlterField(
            model_name='productvendor',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Τιμη Μοναδας'),
        ),
        migrations.AlterField(
            model_name='productvendor',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor', verbose_name='Προμηθευτης'),
        ),
    ]
