# Generated by Django 2.2.4 on 2019-09-20 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190917_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Προϊόντα'},
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='products.Category', verbose_name='Κατηγορίες'),
        ),
        migrations.AlterField(
            model_name='productvendor',
            name='final_value',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Αξια'),
        ),
        migrations.AlterField(
            model_name='productvendor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_vendors', to='products.Product', verbose_name='Προϊον'),
        ),
        migrations.AlterField(
            model_name='productvendor',
            name='sku',
            field=models.CharField(max_length=150, verbose_name='Κωδικος Τιμολογιου'),
        ),
    ]
