# Generated by Django 2.2.4 on 2019-09-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190920_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Προϊόν'},
        ),
        migrations.AlterField(
            model_name='productvendor',
            name='final_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Αξια'),
        ),
        migrations.AlterField(
            model_name='productvendor',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Καθαρή Αξία'),
        ),
    ]
