# Generated by Django 2.2.4 on 2019-12-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20190921_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvendor',
            name='clean_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Καθαρη Αξια'),
        ),
        migrations.AddField(
            model_name='productvendor',
            name='taxes_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Αξια μετα Φορους'),
        ),
        migrations.AlterField(
            model_name='product',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Αρχική Τιμή Πώλησης'),
        ),
        migrations.AlterField(
            model_name='productvendor',
            name='final_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Τελικη Αξια'),
        ),
        migrations.AlterField(
            model_name='productvendor',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Αρχική Αξία'),
        ),
    ]
