# Generated by Django 2.2.4 on 2019-12-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20191207_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvendor',
            name='taxes_value',
        ),
    ]
