# Generated by Django 2.2.4 on 2019-12-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20191207_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
