# Generated by Django 3.0.1 on 2019-12-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20191214_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvendor',
            name='taxes_modifier',
            field=models.CharField(choices=[('a', 0), ('b', 13), ('c', 24)], default='c', max_length=1),
        ),
    ]
