# Generated by Django 2.2.4 on 2020-01-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20200117_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvendor',
            options={'ordering': ['product__title']},
        ),
        migrations.AddField(
            model_name='productvendor',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
