# Generated by Django 3.0.1 on 2020-02-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200123_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvendor',
            options={'ordering': ['-is_favorite', 'product__title']},
        ),
        migrations.AlterField(
            model_name='productvendor',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Αγαπημένο'),
        ),
    ]
